pip3: install mysql-connector-python==8.0.29
The newer version 8.0.30 causes some smoke tests failed with error below

======================================================================
ERROR: test_01_deployVMInSharedNetwork (tests.smoke.test_network.TestSharedNetwork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/marvin/tests/smoke/test_network.py", line 1980, in test_01_deployVMInSharedNetwork
    "select ip4_address from nics where strategy='Placeholder' and ip4_address = '%s';" % routerIp);
  File "/usr/local/lib/python3.6/site-packages/marvin/dbConnection.py", line 45, in execute
    db=str(self.database) if not db else db)) as conn:
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/pooling.py", line 287, in connect
    return MySQLConnection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 137, in __init__
    self.connect(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/abstracts.py", line 1095, in connect
    self._open_connection()
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 544, in _open_connection
    self.set_converter_class(self._converter_class)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/abstracts.py", line 1271, in set_converter_class
    self.converter = convclass(charset_name, self._use_unicode)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/conversion.py", line 136, in __init__
    MySQLConverterBase.__init__(self, charset, use_unicode, str_fallback)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/conversion.py", line 59, in __init__
    self.set_charset(charset)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/conversion.py", line 73, in set_charset
    self.charset_id = CharacterSet.get_charset_info(self.charset)[0]
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/constants.py", line 775, in get_charset_info
    info = cls.get_default_collation(charset)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/constants.py", line 746, in get_default_collation
    raise ProgrammingError(f"Character set '{charset}' unsupported")
mysql.connector.errors.ProgrammingError: Character set 'utf8' unsupported