Marvin: Install mysql-connector-python 8.0.30 for Debian/SUSE
To fix smoke test failures caused by error

```
import mysql.connector

conn = mysql.connector.connect(
    host="10.0.35.28",
    port=3306,
    user="root",
    password="Pxxxxx",
    database="cloud",
    use_unicode=True,
)

mysql.connector.errors.ProgrammingError: Character set 'utf8' unsupported

```