marvin: install netaddr 0.10.1 as latest 1.0.0 requires Python 3.7.0 or higher
see error below
```
  File "/marvin/tests/smoke/test_affinity_groups.py", line 24, in <module>
    from marvin.lib.common import (get_domain,
  File "/usr/local/lib/python3.6/site-packages/marvin/lib/common.py", line 101, in <module>
    from netaddr import IPAddress
  File "/usr/local/lib/python3.6/site-packages/netaddr/__init__.py", line 16, in <module>
    raise RuntimeError('Python 3.7.0 or higher is required!')
RuntimeError: Python 3.7.0 or higher is required!
```